export {default as Accounts} from './Admin-Accounts/Accounts'
export {default as ChapterInstall} from './ChapterInstall/ChapterInstall'
export {default as ChapterUpload} from './ChapterUpload/ChapterUpload'
export {default as Course} from './Courses/Course'
export {default as MakeExam} from './MakeExam/MakeExam'
export {default as ExamPreview} from './ExamPreview/ExamPreview'
export {default as ExamResults} from './ExamResults/ExamResults'
export {default as ExamResultDetails} from './ExamResultDetails/ExamResultDetails'
export {default as Home} from './Home/Home'
export {default as SignIn} from './SignIn/SignIn'
export {default as AdminCourses} from "./Admin-Courses/AdminCourses";
export {default as Profile} from "./Profile/Profile";
export {default as Assignments} from './Assignments/Assignments';
export {default as UploadAssignment} from './UploadAssignment/UploadAssignment';
export {default as TakeExam} from './TakeExam/TakeExam';
export {default as AllNotifications} from './AllNotifications/AllNotifications';
export {default as ViewStudentExam} from './ViewStudentExam/ViewStudentExam';